language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

addons:
  apt:
    packages:
      - expect
      - zsh

install: pip install -r requirements.txt --no-use-wheel

script:
  - coverage run --source ish -m unittest discover
  - coverage report -m --fail-under=100
  - ./test.expect
